CREATE PROC [dbo].[update_location](
    @id                 Int,
	@name				varchar(120) = NULL,
	@site_size			decimal(13) = NULL,
	@pm_site_code	    varchar(20) = NULL,
	@type				Int = NULL,
	@premise			varchar(30) = NULL,
	@ddbt			    varchar(50) = NULL,
	@desired_head_count Int = NULL,
	@is_active          Int = NULL,
	@phone              varchar(20) = NULL, 
    @phone_ext          varchar(10) = NULL, 
    @email              varchar(200) = NULL,
    @line_1				varchar(120)= NULL,
	@line_2				varchar(120)= NULL,
	@line_3				varchar(120)= NULL,
	@city				varchar(60)= NULL,
	@state				varchar(60)= NULL,
	@country			varchar(3)= NULL,
	@zip				varchar(20)= NULL,
	@po_box_number		varchar(20)= NULL,
	@verified_freeform_address      varchar(300) = NULL,
	@hash_of_verified_address       varchar(50) = NULL,
	@verified_line_1				varchar(120)= NULL,
	@verified_line_2				varchar(120)= NULL,
	@verified_line_3				varchar(120)= NULL,
	@verified_city				varchar(60)= NULL,
	@verified_state				varchar(60)= NULL,
	@verified_country			varchar(3)= NULL,
	@verified_zip				varchar(20)= NULL,
	@verified_po_box_number		varchar(20)= NULL,
	@is_using_verified		BIT= NULL,
	@receives_offsite_gilts     BIT = NULL,
	@updated_by			varchar(120),
	@updated_by_action 	char(32))
AS
BEGIN
	SET NOCOUNT ON;
	 UPDATE locations  
       SET name = COALESCE(@name, name),
          site_size = COALESCE(@site_size, site_size),
          pm_site_code = COALESCE(@pm_site_code, pm_site_code),
          type = COALESCE(@type, type),
          premise_id = COALESCE(@premise, premise_id),
          ddbt = COALESCE(@ddbt, ddbt),
          is_active = COALESCE(@is_active, is_active),
          desired_head_count= COALESCE(@desired_head_count, desired_head_count),
          phone = COALESCE(@phone, phone),
          phone_ext = COALESCE(@phone_ext, phone_ext),
          email = COALESCE(@email, email),
          line_1 = COALESCE(@line_1, line_1),
          line_2 = COALESCE(@line_2, line_2),
          line_3 = COALESCE(@line_3, line_3),
          city = COALESCE(@city, city),
          state = COALESCE(@state, state),
          country = COALESCE(@country, country),
          zip = COALESCE(@zip, zip),
          po_box_number = COALESCE(@po_box_number, po_box_number),
           verified_freeform_address= COALESCE(@verified_freeform_address, verified_freeform_address),
		 hash_of_verified_address= COALESCE(@hash_of_verified_address, hash_of_verified_address),
          verified_line_1 = COALESCE(@verified_line_1, verified_line_1),
          verified_line_2 = COALESCE(@verified_line_2, verified_line_2),
          verified_line_3 = COALESCE(@verified_line_3, verified_line_3),
          verified_city = COALESCE(@verified_city, verified_city),
          verified_state = COALESCE(@verified_state, verified_state),
          verified_country = COALESCE(@verified_country, verified_country),
          verified_zip = COALESCE(@verified_zip, verified_zip),
          verified_po_box_number = COALESCE(@verified_po_box_number, verified_po_box_number),
          is_using_verified = COALESCE(@is_using_verified, is_using_verified),
          receives_offsite_gilts = COALESCE(@receives_offsite_gilts, receives_offsite_gilts),
          [_updated_by]=  @updated_by,
          [_updated_by_action] = @updated_by_action 
          WHERE id = @id;
END;
GO

